### ISSUE TITLE
Crash after approaching Alpha Yeti from Twilight Forest mod (ticking entity) (onEntityPlace)

### ISSUE THREAD

**Issue by deadlymango** [dainxt/DungeonsMod-Issue-Tracker#33]
I am playing on a server and connecting via client.
Minecraft version: 1.16.5
Forge version: 36.2.0
Dungeons Mod version: 1.16.3-1.4.38 (also happens on 1.16.3-1.4.40)
Twlight Forest version: 1.16.5-4.0.515-universal

When I approach the Alpha Yeti (just loading the Yeti in, not even fighting it), the server crashes with the following output in the latest.log file.

---

[31Aug2021 21:18:03.047] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 6
	Listeners:
		0: HIGH
		1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		2: NORMAL
		3: ASM: com.song.castle_in_the_sky.events.ServerEvents@70f5e368 onBlockPlaced(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		4: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@4b24b869 onPlaceBlock(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		5: ASM: class com.legacy.blue_skies.events.SkiesPlayerEvents onPlayerPlaceBlock(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		6: ASM: com.dainxt.dungeonsmod.handlers.EventsHandler@1de48916 onEntityPlace(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		7: ASM: class com.teammetallurgy.atum.misc.event.AtumEventListener onPlace(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		8: ASM: class com.teammetallurgy.atum.blocks.stone.limestone.chest.SarcophagusBlock onPlaced(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		9: ASM: io.github.ahydul.core.event.EventHandler@64f6ae42 onPlacedBlock(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		10: ASM: class com.minecraftabnormals.environmental.common.item.explorer.ArchitectBeltItem placeBlockEvent(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		11: ASM: com.teammetallurgy.atum.world.gen.structure.pyramid.PyramidStructure@2a5d70ec onBlockPlaced(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		12: ASM: com.tm.calemiutils.event.WrenchEvent@ea17d2f onBlockPlace(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		13: ASM: com.tm.calemiutils.event.SecurityEvent@34717b29 onBlockPlace(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
		14: LOWEST
		15: ASM: class harmonised.pmmo.events.EventHandler blockPlaced(Lnet/minecraftforge/event/world/BlockEvent$EntityPlaceEvent;)V
**java.lang.NullPointerException
	at com.dainxt.dungeonsmod.handlers.EventsHandler.onEntityPlace(EventsHandler.java:226)**
	at net.minecraftforge.eventbus.ASMEventHandler_1244_EventsHandler_onEntityPlace_EntityPlaceEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at twilightforest.entity.boss.IceBombEntity.doTerrainEffects(IceBombEntity.java:58)
	at twilightforest.entity.boss.IceBombEntity.func_70227_a(IceBombEntity.java:42)
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:67)
	at twilightforest.entity.boss.IceBombEntity.func_70071_h_(IceBombEntity.java:87)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
	at net.minecraft.world.World.func_217390_a(World.java:1684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:829)

[31Aug2021 21:18:03.053] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 44166888-7cc8-4843-9816-838417470cfe
**[31Aug2021 21:18:03.058] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity**
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
**Caused by: java.lang.NullPointerException
	at com.dainxt.dungeonsmod.handlers.EventsHandler.onEntityPlace(EventsHandler.java:226) ~[dungeonsmod:1.16.3-1.4.38]**
	at net.minecraftforge.eventbus.ASMEventHandler_1244_EventsHandler_onEntityPlace_EntityPlaceEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at twilightforest.entity.boss.IceBombEntity.doTerrainEffects(IceBombEntity.java:58) ~[twilightforest:?]
	at twilightforest.entity.boss.IceBombEntity.func_70227_a(IceBombEntity.java:42) ~[twilightforest:?]
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:67) ~[?:?]
	at twilightforest.entity.boss.IceBombEntity.func_70071_h_(IceBombEntity.java:87) ~[twilightforest:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:1684) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more

---

I don't have reason to believe any mod other than Twilight Forest and Dungeons Mod is interfering, but here is the mod list anyway.

Mod List:
Mods: Falling Attack, YUNG's Better Dungeons, Second Chance Forge, FTB Essentials, Big Brain, DeleteItem, Infernal Expansion, Areas, PiratesAndLootersReborn, Timeless and Classic Mod Addon, Just Another Void Dim, ToroHealth, Stalwart Dungeons, Help Wanted, YUNG's Better Caves, Rising Uppercut, Forge Endertech, Villager Death Messages, Colds: Tempered Netherite, Modern Life, YUNG's API, MaxHealthFix, Extra Potions, Guard Villagers, RandomPatches, Apotheosis, Deathmatch, Morpheus, ForageCraft, Flood, Snow! Real Magic!, Just Enough Resources, Throwable Explosives, Paraglider, ShetiPhian-Core, Supplementaries, Enhanced Snowman, BetterEnd Forge, Upgraded Netherite, Structure Gel API, Castle in the sky, Better Ping Display, Repurposed Structures, More Villagers, Biomes O' Plenty, ToolStats, Property Modifier, StumbleUponCamps, Spawner Fix, Corpse Complex, Modular Enchantments, Curios API, GameStages, Unique Enchantments, Obfuscate, Chunk Pregenerator, WorldEdit, Sapience, Project MMO, Infernal BugZ, Cloth Config v4 API, Enhanced AI, Exotic Birds, Disenchanting, YUNG's Better Mineshafts, PlayerRevive, GeckoLib, Dungeons Gear, Colds Enchants 2.0, Kiwi, Mowzie's Mobs, Skin Changer, Example Mod, MrCrayfish's Gun Mod, Mining Helmet, Calemi's Utils, Just Enough Items, AttributeFix, Banyan Forest, Shock Metal, Realistic Explosion Physics, Traveler's Backpack, Serene Seasons, Stoneholm, Creeper AI Updated, Upstream, Advanced Hook Launchers, Curio of Undying, JEI Tweaker, CraftTweaker, More Tool Materials, Forge, Atum 2, Vending Machine, Blame!, Subterranean Wilderness, Dynamic Surroundings, Dynamic Surroundings: Sound Control, Dynamic Surroundings: Environs, Dynamic Surroundings: Mob Effects, TellMe, Iron Chests, Axes Are Weapons, When Dungeons Arise, CoFH Core, Simple Voice Chat, Classes, Nutritious Milk, CrimsonNBTTags, Custom Professions, Large Ore Deposits, AstikorCarts, Majrusz Library, Farming in Rain, Whisperwoods, Mantle, Xaero's Minimap, Gravestone Mod, Polymorph, AutoRegLib, Regrowth Mod, Illumination, Wesley's Roguelike Dungeons, TorchBowMod, AppleSkin, Lootr, Water Erosion, Oh The Biomes You'll Go, Aquaculture 2, Villagers Respawn  Mod, Orcinus's Cavern, Better Invisibility, Terraqueous, TerraHeads, PixelPowers, Stupid Weapons, Chinese Style Sword, Parrying, The Farlanders, Default Options, Dungeons Mod, Food Expansion: Reimagined, Blue Skies, Hats, InControl, Deadly End Phantoms, Wonderful Enchantments, InsaneLib, Farsight, Villager Names, TerraForged, Configurable Extra Mob Drops, Xaero's World Map, Controlling, Placebo, Citadel, Alex's Mobs, Ice and Fire, Custom Villager Trades, Mutant Beasts, Micle's Login Protection, Bookshelf, Fabrication, Simple Planes, Relics, Progressive Bosses, The Twilight Forest, Konkrete, Ore Tweaker, Chocolate, Macaw's Bridges, Customizable Elytra, Things that go Boom!, Warped Potion, Project: Vibrant Journeys, End Remastered 3.6, Mining World, Elenai Dodge 2, Simply Light, Simple Farming, Jousting, Dungeons Enhanced, Village Spawn Point, heartbalance, Bountiful, Patchouli, Ars Nouveau, Leap, Collective, Velocity Based Damage, Flan, HT's TreePlant, villagertools, Desolation (Forge), More Ores Armors and Tools, Traveler's Index, Starter Kit, Spartan Weaponry, Architectury, FTB GUI Library, FTB Teams, The Undergarden, Small Ships Mod, Legacy Vault, GottschCore, Observable, When Was That Again, Unique Enchantments Base, BedBenefits, Cursed, Spiders 2.0, Giant Spawn, Soaring Structures 2 , Abnormals Core, Environmental, The Endergetic Expansion, Neapolitan, Personality, Savage & Ravage, Allurement, Brazier, Extra Boats, UNDEAD, Waystones, Weapon Throw, FastSuite, Nasty Mobs, Colds: Ostriches, Artifacts, Custom Player Model, The Outer End, Dungeon Crawl, Better Animals Plus, Farsighted Mobs, Bottle Your Xp, Hyper Lighting, iChunUtil, Villagers Follow Emeralds, Player based spawners, Ultra Amplified Dimension, Death Backup, Untitled Duck Mod, Selene, Useless Sword, Inspirations, Horse Combat Controls, EnchantmentDescriptions, CreativeCore, Villager Trades, Archer's Paradox, Towers Of The Wild, Llama Steeds, Spartan Shields, Quark, Charm, Diet, Mob Sunscreen, Random Village Names, Inventory HUD+(Forge edition), Illagers Wear Armor, Combustive Fishing, FancyMenu, World Stripper, InfinityLib, Ferrite Core, Enhanced Celestials, Illagers+, ExpandAbility, Valhelsia Core, Valhelsia Structures, Overloaded Armor Bar

**Comment by dainxt** [comment]
Twlight Forest version: 1.16.5-4.0.546 just fixed this crash
