### ISSUE TITLE
ItemStack Error

### ISSUE THREAD

**Issue by IronPhoenixBlade** [dainxt/DungeonsMod-Issue-Tracker#38]
I run a 1.17 server which uses the mod and we've had a similar crash with two bosses (the Frost Walker and the Iron Slime). Here's the stack trace that happened when I hit the Iron Slime with a Diamond Sword:
java.lang.NoSuchMethodError: 'java.util.Set net.minecraft.world.item.ItemStack.getToolTypes()'
	at com.dainxt.dungeonsmod.entity.boss.EntityIronSlime.m_6469_(EntityIronSlime.java:174) ~[DungeonsMod-1.17.1-1.4.40.jar%2358!:1.17.1-1.4.40] {re:classloading}
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1115) ~[client-1.17.1-20210706.113038-srg.jar%2367!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105223_(MultiPlayerGameMode.java:361) ~[client-1.17.1-20210706.113038-srg.jar%2367!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91276_(Minecraft.java:1492) ~[client-1.17.1-20210706.113038-srg.jar%2367!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1825) ~[client-1.17.1-20210706.113038-srg.jar%2367!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1647) ~[client-1.17.1-20210706.113038-srg.jar%2367!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.17.1-20210706.113038-srg.jar%2367!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.17.1-20210706.113038-srg.jar%2367!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2367!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.33.jar%2321!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

What other information would be helpful to help debug this issue?

**Comment by dainxt** [comment]
This was already fixed, update your mod version.
