### ISSUE TITLE
Valhelsia 3 Crashes if you disable spiders throwing webs

### ISSUE THREAD

**Issue by TronWoWGamer** [dainxt/DungeonsMod-Issue-Tracker#45]
Playing Valhelsia 3 for some time and all was fine until I changed the last thing in the config that makes it so that spiders shoot webs.  The default is true and I changed it to false.  After this it keeps crashing with java null pointer exception on Entity Creation.

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.network.datasync.EntityDataManager.func_187225_a(EntityDataManager.java:117) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.entity.monster.SpiderEntity.isWebShooting(SpiderEntity.java:571) ~[?:?] 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.network.datasync.EntityDataManager.func_187225_a(EntityDataManager.java:117) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.entity.monster.SpiderEntity.isWebShooting(SpiderEntity.java:571) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dungeons_mobs.mixins.json:SpiderEntityMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.model.SpiderModel.handler$bbi000$setRotationAngles(SourceFile:535) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dungeons_mobs.mixins.json:SpiderModelMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.model.SpiderModel.func_225597_a_(SourceFile:132) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dungeons_mobs.mixins.json:SpiderModelMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:111) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:43) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:18) ~[?:?] {re:classloading,re:mixin}
-- Entity being rendered --
Details:
	Entity Type: minecraft:spider (net.minecraft.entity.monster.SpiderEntity)
	Entity ID: 1040
	Entity Name: Spider
	Entity's Exact location: 487.82, 42.00, -469.70
	Entity's Block location: World: (487,42,-470), Chunk: (at 7,2,10 in 30,-30; contains blocks 480,0,-480 to 495,255,-465), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

**Comment by dainxt** [comment]
Wrong mod
