### ISSUE TITLE
NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by lingting** [dainxt/DungeonsMod-Issue-Tracker#55]
mc: 1.16.5
dungeons-libraries: 1.16.5-0.0.18
dungeons-modes: 1.16.5-2.12

java.lang.NullPointerException: Ticking entity
	at com.infamous.dungeons_libraries.capabilities.minionmaster.Master.addSummonedMob(Master.java:52) ~[dungeons_libraries:1.16.5-0.0.18-beta] {re:classloading}
	at com.infamous.dungeons_libraries.summon.SummonHelper.addSummonedMob(SummonHelper.java:23) ~[dungeons_libraries:1.16.5-0.0.18-beta] {re:classloading}
	at com.infamous.dungeons_libraries.summon.SummonHelper.summonEntity(SummonHelper.java:44) ~[dungeons_libraries:1.16.5-0.0.18-beta] {re:classloading}
	at com.infamous.dungeons_mobs.entities.blaze.WildfireEntity$SummonBlazesGoal.func_75246_d(WildfireEntity.java:471) ~[dungeons_mobs:1.16.5-2.1.2-beta] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_261] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_261] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_261] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_261] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_261] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_261] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_261] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_261] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_261] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_261] {}

**Comment by lingting** [comment]
When: Attacking Pigs

**Comment by dainxt** [comment]
The crash was provoked by another mod, but provide your findings here https://github.com/Infamous-Misadventures/Dungeons-Libraries/issues
